//auto generated by go-cli

package config

import (
	_ "embed"
	"github.com/candbright/go-core/config"
)

//go:embed application.yaml
var AppConfigData []byte

// AppConfig is global config parsed from application.yaml file
var AppConfig *config.Config

func init() {
	cfg, err := config.Parse(AppConfigData, config.YAML)
	if err != nil {
		panic(err)
	}
	AppConfig = cfg
}

func Get(key string) string {
	return AppConfig.Get(key)
}

func GetInt(key string) int {
	return AppConfig.GetInt(key)
}

func GetInt64(key string) int64 {
	return AppConfig.GetInt64(key)
}

func GetBool(key string) bool {
	return AppConfig.GetBool(key)
}
