application:
  name: server-auth
  port: 11100
db:
  retry: 3
  mysql:
    ip:
      default: 127.0.0.1
      env: ${PS_MYSQL_IP}
    port:
      default: 3306
      env: ${PS_MYSQL_PORT}
    username:
      default: root
      env: ${PS_MYSQL_USERNAME}
    password:
      default: 1q2w3e@4R
      env: ${PS_MYSQL_PASSWORD}
    db: auth
    params: ?charset-utf8&parseTime=True&loc=Local
    log:
      windows: D:\log\server-auth\db.log
      linux: /var/log/server-auth/db.log
  redis:
    ip:
      default: 127.0.0.1
      env: ${PS_REDIS_IP}
    port:
      default: 6379
      env: ${PS_REDIS_PORT}
    password:
      default: 1q2w3e@4R
      env: ${PS_REDIS_PASSWORD}
    db: 0
    pool-size: 6
log:
  path:
    windows: D:\log\server-auth\server.log
    linux: /var/log/server-auth/server.log
  level:
    default: info
    env: ${PS_LOG_LEVEL}
